### ISSUE TITLE
Question for function "DUCATI.CacheConstructor.separate_features_idx"

### ISSUE THREAD

**Issue by Changyuan0825** [initzhang/DUCATI_SIGMOD#7]
I would like to ask, why do we need to use randomly generated feature vectors (i.e., fake input)? If I misunderstood, could you please tell me the meaning of the function DUCATI.CacheConstructor.separate_features_idx? The following is your raw code:
```
def separate_features_idx(args, graph):
    separate_tic = time.time()
    train_idx = torch.nonzero(graph.ndata.pop("train_mask")).reshape(-1)
    adj_counts = graph.ndata.pop('adj_counts')
    nfeat_counts = graph.ndata.pop('nfeat_counts')

    # cleanup
    graph.ndata.clear()
    graph.edata.clear()

    # we prepare fake input for all datasets
    fake_nfeat = dgl.contrib.UnifiedTensor(torch.rand((graph.num_nodes(), args.fake_dim), dtype=torch.float), device='cuda')
    fake_label = dgl.contrib.UnifiedTensor(torch.randint(args.n_classes, (graph.num_nodes(), ), dtype=torch.long), device='cuda')

    mlog(f'finish generating random features with dim={args.fake_dim}, time elapsed: {time.time()-separate_tic:.2f}s')
    return graph, [fake_nfeat, fake_label], train_idx, [adj_counts, nfeat_counts]
```

**Comment by initzhang** [comment]
Hi @Changyuan0825 , thanks for your interest in our work!
The main purpose is to save disk storage. Since the time of accessing/caching node features will not be influenced by its actual content, we can verify the training time of DUCATI with random node features and avoid storing/loading them to/from disk. As you can see from the [code here](https://github.com/initzhang/DUCATI_SIGMOD/blob/9cc017f8453a26db72cf5c1c2fa1f4a3c9cee969/preprocess/PA.py#L38), you only need to store and load the adjacency data and avoid writing/reading large nfeat data to/from disk, which saves you a lot of time. However, when verifying accuracy and convergence, you need to load the real node features instead.

**Comment by Changyuan0825** [comment]
I get it. Thank you for your response!
